 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4000
 * Running on http://192.168.1.84:4000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 820-908-501
Traceback (most recent call last):
  File "/Users/tom/r/devops-course/devops-course-module4/3-dast/app.py", line 36, in <module>
    app.run(debug=True, host='0.0.0.0', port=4000)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/r/devops-course/devops-course-module4/3-dast/venv/lib/python3.13/site-packages/flask/app.py", line 662, in run
    run_simple(t.cast(str, host), port, self, **options)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/r/devops-course/devops-course-module4/3-dast/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 1115, in run_simple
    run_with_reloader(
    ~~~~~~~~~~~~~~~~~^
        srv.serve_forever,
        ^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        reloader_type=reloader_type,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/tom/r/devops-course/devops-course-module4/3-dast/venv/lib/python3.13/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
    ~~~~~~~~~~~~~~^^
  File "/Users/tom/r/devops-course/devops-course-module4/3-dast/venv/lib/python3.13/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
termios.error: (4, 'Interrupted system call')
